version: '3'
services:
  web:
    image: 447746596892.dkr.ecr.eu-central-1.amazonaws.com/docker_frontend:latest
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:3001"

  api:
    image: 447746596892.dkr.ecr.eu-central-1.amazonaws.com/docker_backend:latest
    ports:
      - "3001:3001"
    environment:
      KEY: "/run/secrets/key"
    secrets:
      - key

  mongo:
    image: mongo
    ports:
      - "27017:27017"

secrets:
  key:
    file: ./key.txt  # Lokaler Pfad zur Secret-Datei für Entwicklungs-/Testzwecke